### ISSUE TITLE
No Migration found - Error on first run

### ISSUE THREAD

**Issue by ravisojitra** [Dhravya/cloudflare-saas-stack#45]
After hitting `bun run setup` 

Query: select count(*) from "user"
 ⨯ Error: D1_ERROR: no such table: user: SQLITE_ERROR
    at async Page (./src/app/page.tsx:29:23)
digest: "4057397386"
Cause: Error: no such table: user: SQLITE_ERROR
    at D1Database._sendOrThrow (cloudflare-internal:d1-api:67:24)
    at async D1PreparedStatement.raw (cloudflare-internal:d1-api:184:32) {
  [cause]: undefined

**Comment by patriciobcs** [comment]
I fixed by replacing some lines in the setup script:

https://github.com/Dhravya/cloudflare-saas-stack/blob/836b4c2b3daab6fad2e3281c354fac681cbe6dd2/scripts/setup.ts#L324

Change to

```executeCommand(`bunx wrangler d1 execute ${dbName} --local --file=./drizzle/0000_setup.sql`);```

 https://github.com/Dhravya/cloudflare-saas-stack/blob/836b4c2b3daab6fad2e3281c354fac681cbe6dd2/scripts/setup.ts#L324

Change to

``` executeCommand(`bunx wrangler d1 execute ${dbName} --remote --file=./drizzle/0000_setup.sql`);```

**Comment by ravisojitra** [comment]
Thanks @patriciobcs, It worked.
